In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import cPickle as pkl
import cv2
import seaborn as sns

from PIL import Image, ImageFilter

In [2]:
X = np.load('/data2/nathan/embryo/patientFeat.npy')
Y = np.load('/data2/nathan/embryo/patientLabel.npy')

In [7]:
sum = [0 for i in range(15)]
for i in range(len(Y)):
    sum += (np.sum(Y[i], axis=0))
sum = np.asarray(sum)

In [13]:
classSum = []
for bin in bins:
    classSum.append(np.sum(sum[bin]))

In [11]:
bins = [[0,1],
        [2,3],
        [4],
        [5,6,7],
        [8],
        [9],
        [10, 11],
        [12, 13],
        [14]]

In [73]:
Y_bin = np.load('/data2/nathan/embryo/patientLabelBin.npy')

In [74]:
for i in range(len(Y_bin)):
    print(np.sum(Y_bin[i], axis=0))

[ 245  604 1297  198  378  567 1401]
[328 475 666 659 965 438 956]
[366 354 823 324 269 390 131]
[ 481  508  930  280  827  924 1218]


In [181]:
sum = [0, 0, 0, 0, 0, 0, 0]
for i in [0,1,2,3]:
    sum += (np.sum(Y_bin[i], axis=0))
sum

array([1420, 1941, 3716, 1461, 2439, 2319, 3706])

In [160]:
res = []
for i in range(len(Y)):
    res.append(np.sum(Y[i], axis=0))
classSum = np.sum(res, axis=0)
len(classSum)

15

In [180]:
res = []
for i in range(len(Y)):
    res.append(np.sum(Y[i], axis=0))
np.sum(res)

17002

In [14]:
sns.despine()
sns.set_style("ticks")
sns.set_style("white")
sns.set_context("paper")
#colors = ['g' if val > 0 else 'r' for val in regModel.coef_[np.abs(regModel.coef_).argsort()[::-1]][:30][::-1]]
plt.barh(np.arange(15), classSum[::-1])
plt.yticks(np.arange(15)+0.5, labels[::-1],fontsize=12)
plt.xlabel('Number of Frames',fontsize=12)
plt.ylabel('Morphokinetic Stage',fontsize=12)
#plt.title("Distribution of Morphokinetic Stage")
plt.ylim(-0.5, 15.3)
plt.show()

ValueError: incompatible sizes: argument 'width' must be length 15 or scalar

In [165]:
classSum

array([ 966,  454, 1730,  211, 2015,  977,  380,  344, 1461, 2439, 1547,
        772, 1162,  746, 1798])

In [80]:
1.0*np.sum(Y_bin[2], axis=0)/np.sum(Y_bin[2])

array([ 0.13774934,  0.13323297,  0.30974784,  0.12194204,  0.101242  ,
        0.14678209,  0.04930373])

In [53]:
np.where(label==1)[0][0]

0

In [98]:
X_train = np.load('/data2/nathan/embryo/train/feat.npy')
Y_train = np.load('/data2/nathan/embryo/train/label.npy')
X_val = np.load('/data2/nathan/embryo/val/feat.npy')
Y_val = np.load('/data2/nathan/embryo/val/label.npy')
X_test = np.load('/data2/nathan/embryo/test/feat.npy')
Y_test = np.load('/data2/nathan/embryo/test/label.npy')

In [139]:
X_train96 = np.load('/data2/nathan/embryo/train/feat96.npy')

In [178]:
len(X_train)

12910

In [176]:
len(X_val)

1435

In [177]:
len(X_test)

2657

In [143]:
a = [exm.flatten() for exm in X_train96]

In [146]:
len(a[0])

9216

In [149]:
np.where(Y_train[0]==1)[0][0]

0

In [152]:
np.argmax(Y_train[1000])

2

In [153]:
Y_train[1000]

array([0, 0, 1, 0, 0, 0, 0])

In [226]:
max(X_train96[0])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [233]:
max(X_train96[200].flatten())

161

In [234]:
a = np.load('/data2/nathan/embryo/val/featFlat.npy')

In [242]:
max(a[100])

152

In [14]:
X = pkl.load(open('/data2/nathan/embryo/patientFeat.pkl'))
Y = pkl.load(open('/data2/nathan/embryo/patientLabelBin.pkl'))

In [10]:
np.sum(Y[1,1], axis=0)

array([ 45,  66, 110,   1, 248,  75, 173])

In [11]:
for ((p,w), v) in Y.iteritems():
    print (str(p) + 'p ' + str(w) + 'w: ' + str(np.sum(v, axis=0)))

1p 3w: [ 68  59  99  89 127  49  34]
0p 7w: [ 26  81 178 198   3  39  74]
1p 6w: [ 43  66  90 110 134  91  29]
3p 7w: [ 63  70  92  94  69  84 253]
2p 5w: [ 57  74 187   0   0 185  73]
0p 3w: [ 22  76   3   0 144  61 234]
1p 2w: [ 36  63  83  92 120  43 281]
3p 3w: [ 59  77 109   0 131 141 181]
1p 5w: [ 49  77 109 163 127  30 163]
0p 11w: [ 26  72  79   0 119  46 273]
2p 2w: [ 68  85 194  18 112  90  58]
1p 1w: [ 45  66 110   1 248  75 173]
3p 2w: [129 138 324  68 203 183  51]
2p 6w: [ 37  85 156  23 157 115   0]
0p 4w: [ 28  67 190   0   0  56 184]
1p 4w: [ 38  70  88 108  76 106  41]
0p 12w: [ 35  79 171   0   0  71 221]
3p 9w: [ 57   7 146   0  40 114 231]
2p 1w: [79  4 74  9  0  0  0]
0p 8w: [ 35  18 232   0   0  72 116]
2p 7w: [  0  10 195 274   0   0   0]
3p 12w: [11  0  0  0  0  0  0]
3p 1w: [ 52  67  86  91 109 140 179]
0p 2w: [ 23  71 190   0   0  84 146]
3p 8w: [ 67  74  92   6 166 123  67]
0p 6w: [ 25  67  67   0 112  56 146]
1p 7w: [ 49  74  87  96 133  44 235]
0p 9w: [ 25 

In [21]:
a = [0,0,0,0,0,0,0]
for k in [(1,3), (0, 7), (3, 8)]:
    a += np.sum(Y[k], axis=0)
a

array([161, 214, 369, 293, 296, 211, 175])

In [20]:
np.sum(a)

1719

In [22]:
Y_val = np.load('/data2/nathan/embryo/val/label.npy')

In [23]:
np.sum(Y_val, axis=0)

array([161, 214, 369, 293, 296, 211, 175])

In [28]:
np.sum(Y_val)

1719

In [25]:
Y_train = np.load('/data2/nathan/embryo/train/label.npy')

In [26]:
np.sum(Y_train, axis=0)

array([1259, 1727, 3347, 1168, 2143, 2108, 3531])

In [27]:
np.sum(Y_train)

15283

In [30]:
Y_test = np.load('/data2/nathan/embryo/test/label.npy')

In [31]:
np.sum(Y_test, axis=0)

array([366, 354, 823, 324, 269, 390, 131])

In [32]:
np.sum(Y_test)

2657